// deno-fmt-ignore-file
// biome-ignore format: generated types do not need formatting
// prettier-ignore
import type { PathsForPages } from 'waku/router'

// prettier-ignore
type Page =
  | { path: '/api/generated/agent/src/classes/Nostr'; render: 'static' }
  | { path: '/api/generated/agent/src/classes/NostrClient'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/createIdentity'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/decide'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/extractContent'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/loadIdentity'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/parseDecision'; render: 'static' }
  | { path: '/api/generated/agent/src/functions/runAgent'; render: 'static' }
  | { path: '/api/generated/agent/src'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/DM'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/FeedNote'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/Identity'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/Persona'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/PublishOk'; render: 'static' }
  | { path: '/api/generated/agent/src/interfaces/RunAgentOptions'; render: 'static' }
  | { path: '/api/generated/agent/src/type-aliases/CopilotRunner'; render: 'static' }
  | { path: '/api/generated/agent/src/type-aliases/Decision'; render: 'static' }
  | { path: '/api/generated/agent/src/variables/DEFAULT_RELAYS'; render: 'static' }
  | { path: '/api/generated/agent/src/variables/copilotRunner'; render: 'static' }
  | { path: '/api/generated/client/src/classes/Nostr'; render: 'static' }
  | { path: '/api/generated/client/src/classes/PublishThunk'; render: 'static' }
  | { path: '/api/generated/client/src/functions/storeBackedPolicy'; render: 'static' }
  | { path: '/api/generated/client/src'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/EventTemplate'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/Filter'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/NostrEvent'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/NostrOptions'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/PoolPublishResult'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/PublishDriver'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/Signer'; render: 'static' }
  | { path: '/api/generated/client/src/interfaces/Subscription'; render: 'static' }
  | { path: '/api/generated/client/src/type-aliases/Pubkey'; render: 'static' }
  | { path: '/api/generated/client/src/variables/DEFAULT_RELAYS'; render: 'static' }
  | { path: '/api/generated/core/src/classes/TemplateBuilder'; render: 'static' }
  | { path: '/api/generated/core/src/functions/addressOf'; render: 'static' }
  | { path: '/api/generated/core/src/functions/brandEventFields'; render: 'static' }
  | { path: '/api/generated/core/src/functions/build'; render: 'static' }
  | { path: '/api/generated/core/src/functions/buildNote'; render: 'static' }
  | { path: '/api/generated/core/src/functions/bytesToHex'; render: 'static' }
  | { path: '/api/generated/core/src/functions/bytesToUtf8'; render: 'static' }
  | { path: '/api/generated/core/src/functions/classifyKind'; render: 'static' }
  | { path: '/api/generated/core/src/functions/concatBytes'; render: 'static' }
  | { path: '/api/generated/core/src/functions/countLeadingZeroBits'; render: 'static' }
  | { path: '/api/generated/core/src/functions/createIdentity'; render: 'static' }
  | { path: '/api/generated/core/src/functions/finalizeEvent'; render: 'static' }
  | { path: '/api/generated/core/src/functions/getEventHash'; render: 'static' }
  | { path: '/api/generated/core/src/functions/getPublicKey'; render: 'static' }
  | { path: '/api/generated/core/src/functions/hasValidId'; render: 'static' }
  | { path: '/api/generated/core/src/functions/hexToBytes'; render: 'static' }
  | { path: '/api/generated/core/src/functions/isAddressable'; render: 'static' }
  | { path: '/api/generated/core/src/functions/isEphemeral'; render: 'static' }
  | { path: '/api/generated/core/src/functions/isHex64'; render: 'static' }
  | { path: '/api/generated/core/src/functions/isReplaceable'; render: 'static' }
  | { path: '/api/generated/core/src/functions/loadIdentity'; render: 'static' }
  | { path: '/api/generated/core/src/functions/matchFilter'; render: 'static' }
  | { path: '/api/generated/core/src/functions/matchFilters'; render: 'static' }
  | { path: '/api/generated/core/src/functions/mine'; render: 'static' }
  | { path: '/api/generated/core/src/functions/npubOf'; render: 'static' }
  | { path: '/api/generated/core/src/functions/parseEventId'; render: 'static' }
  | { path: '/api/generated/core/src/functions/parsePubkey'; render: 'static' }
  | { path: '/api/generated/core/src/functions/parseSecretKeyHex'; render: 'static' }
  | { path: '/api/generated/core/src/functions/parseSignature'; render: 'static' }
  | { path: '/api/generated/core/src/functions/randomBytes'; render: 'static' }
  | { path: '/api/generated/core/src/functions/secretHex'; render: 'static' }
  | { path: '/api/generated/core/src/functions/serializeEvent'; render: 'static' }
  | { path: '/api/generated/core/src/functions/toSecretBytes'; render: 'static' }
  | { path: '/api/generated/core/src/functions/utf8ToBytes'; render: 'static' }
  | { path: '/api/generated/core/src/functions/verifyEvent'; render: 'static' }
  | { path: '/api/generated/core/src'; render: 'static' }
  | { path: '/api/generated/core/src/interfaces/EventTemplate'; render: 'static' }
  | { path: '/api/generated/core/src/interfaces/Filter'; render: 'static' }
  | { path: '/api/generated/core/src/interfaces/Identity'; render: 'static' }
  | { path: '/api/generated/core/src/interfaces/NostrEvent'; render: 'static' }
  | { path: '/api/generated/core/src/interfaces/UnsignedEvent'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decode'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNaddr'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNevent'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNote'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNprofile'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNpub'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/decodeNsec'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNaddr'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNevent'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNote'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNprofile'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNpub'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/functions/encodeNsec'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/AddressPointer'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/AddressPointerInput'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/EventPointer'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/EventPointerInput'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/ProfilePointer'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/interfaces/ProfilePointerInput'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip19/type-aliases/DecodedEntity'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip21/functions/decodeUri'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip21/functions/toEntity'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip21/functions/toUri'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip21'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/calcPaddedLen'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/decrypt'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/decryptFrom'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/encrypt'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/encryptTo'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/getConversationKey'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44/functions/getMessageKeys'; render: 'static' }
  | { path: '/api/generated/core/src/namespaces/nip44'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/Branded'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/EventId'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/KindClass'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/Pubkey'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/SecretKeyHex'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/Signature'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/Tag'; render: 'static' }
  | { path: '/api/generated/core/src/type-aliases/VerifiedEvent'; render: 'static' }
  | { path: '/api/generated/core/src/variables/base64'; render: 'static' }
  | { path: '/api/generated/core/src/variables/isParameterizedReplaceable'; render: 'static' }
  | { path: '/api/generated/core/src/variables/sha256'; render: 'static' }
  | { path: '/api/generated'; render: 'static' }
  | { path: '/api/generated/pool/src/classes/Pool'; render: 'static' }
  | { path: '/api/generated/pool/src/classes/Subscription'; render: 'static' }
  | { path: '/api/generated/pool/src'; render: 'static' }
  | { path: '/api/generated/pool/src/interfaces/PoolOptions'; render: 'static' }
  | { path: '/api/generated/pool/src/interfaces/PoolPublishResult'; render: 'static' }
  | { path: '/api/generated/pool/src/interfaces/PoolSubscribeOptions'; render: 'static' }
  | { path: '/api/generated/pool/src/type-aliases/SubscriptionEvent'; render: 'static' }
  | { path: '/api/generated/relay/src/classes/Relay'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/buildAuthTemplate'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/clampLimit'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/fetchRelayInformation'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/infoUrl'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/parseRelayMessage'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/reasonPrefix'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/serializeClientMessage'; render: 'static' }
  | { path: '/api/generated/relay/src/functions/supportsNip'; render: 'static' }
  | { path: '/api/generated/relay/src'; render: 'static' }
  | { path: '/api/generated/relay/src/interfaces/PublishResult'; render: 'static' }
  | { path: '/api/generated/relay/src/interfaces/RelayInformation'; render: 'static' }
  | { path: '/api/generated/relay/src/interfaces/RelayOptions'; render: 'static' }
  | { path: '/api/generated/relay/src/interfaces/SubscribeHandlers'; render: 'static' }
  | { path: '/api/generated/relay/src/interfaces/WebSocketLike'; render: 'static' }
  | { path: '/api/generated/relay/src/type-aliases/ClientMessage'; render: 'static' }
  | { path: '/api/generated/relay/src/type-aliases/ConnectionState'; render: 'static' }
  | { path: '/api/generated/relay/src/type-aliases/ReasonPrefix'; render: 'static' }
  | { path: '/api/generated/relay/src/type-aliases/RelayMessage'; render: 'static' }
  | { path: '/api/generated/relay/src/type-aliases/WebSocketFactory'; render: 'static' }
  | { path: '/api/generated/router/src/classes/Router'; render: 'static' }
  | { path: '/api/generated/router/src/functions/hintsFromPointer'; render: 'static' }
  | { path: '/api/generated/router/src/functions/hintsFromTags'; render: 'static' }
  | { path: '/api/generated/router/src/functions/normalizeRelayUrl'; render: 'static' }
  | { path: '/api/generated/router/src/functions/parseRelayList'; render: 'static' }
  | { path: '/api/generated/router/src/functions/readRelays'; render: 'static' }
  | { path: '/api/generated/router/src/functions/writeRelays'; render: 'static' }
  | { path: '/api/generated/router/src'; render: 'static' }
  | { path: '/api/generated/router/src/interfaces/RelayListEntry'; render: 'static' }
  | { path: '/api/generated/router/src/interfaces/RouterPolicy'; render: 'static' }
  | { path: '/api/generated/router/src/interfaces/Selection'; render: 'static' }
  | { path: '/api/generated/signers/src/classes/BunkerSigner'; render: 'static' }
  | { path: '/api/generated/signers/src/classes/LocalSigner'; render: 'static' }
  | { path: '/api/generated/signers/src/classes/Nip07Signer'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/bunkerSigner'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/decryptKey'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/decryptKeyHex'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/encryptKey'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/fromPayload'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/generateSeedWords'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/nip04Decrypt'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/nip07Signer'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/parseBunkerUri'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/privateKeyFromSeedWords'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/privateKeyHexFromSeedWords'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/privateKeySigner'; render: 'static' }
  | { path: '/api/generated/signers/src/functions/validateWords'; render: 'static' }
  | { path: '/api/generated/signers/src'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/BunkerOptions'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/FromPayloadDeps'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/Nip07Provider'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/Nip46Transport'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/Signer'; render: 'static' }
  | { path: '/api/generated/signers/src/interfaces/SignerPayload'; render: 'static' }
  | { path: '/api/generated/signers/src/type-aliases/KeySecurity'; render: 'static' }
  | { path: '/api/generated/signers/src/type-aliases/SignerBackend'; render: 'static' }
  | { path: '/api/generated/store/src/classes/EventStore'; render: 'static' }
  | { path: '/api/generated/store/src'; render: 'static' }
  | { path: '/api/generated/store/src/interfaces/EventStoreOptions'; render: 'static' }
  | { path: '/api/generated/store/src/interfaces/StoreBackend'; render: 'static' }
  | { path: '/api/generated/store/src/type-aliases/AddResult'; render: 'static' }
  | { path: '/api'; render: 'static' }
  | { path: '/guide/agent'; render: 'static' }
  | { path: '/guide/dms'; render: 'static' }
  | { path: '/guide/getting-started'; render: 'static' }
  | { path: '/guide/nips'; render: 'static' }
  | { path: '/guide/outbox'; render: 'static' }
  | { path: '/guide/publishing'; render: 'static' }
  | { path: '/guide/signers'; render: 'static' }
  | { path: '/guide/subscriptions'; render: 'static' }
  | { path: '/'; render: 'static' }
  | { path: '/live'; render: 'static' }
  | { path: '/nips-coverage'; render: 'static' }
  | { path: '/packages/agent'; render: 'static' }
  | { path: '/packages/client'; render: 'static' }
  | { path: '/packages/core'; render: 'static' }
  | { path: '/packages/nips'; render: 'static' }
  | { path: '/packages/pool'; render: 'static' }
  | { path: '/packages/relay'; render: 'static' }
  | { path: '/packages/router'; render: 'static' }
  | { path: '/packages/signers'; render: 'static' }
  | { path: '/packages/store'; render: 'static' }

// prettier-ignore
declare module 'waku/router' {
  interface RouteConfig {
    paths: PathsForPages<Page>
  }
  interface CreatePagesConfig {
    pages: Page
  }
}
